# Base blog settings
baseurl                      : "/dact" # the subpath of your site,                         # e.g. /blog/
                              # set to '' in case of hosting on GitHub
url                          : "https://m0nica.github.io" # the base hostname & protocol for your site
                                  # `http://<username>.github.io` - for GitHub
